# Generated by Django 5.0.6 on 2026-07-07 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='residentmapping',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_mapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentmapping',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentmapping',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society'),
        ),
        migrations.AddField(
            model_name='block',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='society.society'),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('block', 'flat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('society', 'name')},
        ),
    ]
