# Generated by Django 5.0.6 on 2026-07-07 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_contact_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='resident',
            field=models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactotpverification',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='emergency.emergencycontact'),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_type', 'PRIMARY_GUARDIAN')), fields=('resident', 'contact_type'), name='unique_primary_guardian_per_resident'),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_type', 'SECONDARY_GUARDIAN')), fields=('resident', 'contact_type'), name='unique_secondary_guardian_per_resident'),
        ),
    ]
